### ISSUE TITLE
Crash with Api 23 on Galaxy Nexus Emulator

### ISSUE THREAD

**Issue by mario-s** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#12]
When I try to run the demo application on a emulator which uses the API 23 I get the following exception and the app crashes:
`D/SDKRelativeJNI: Couldn't load lib
E/art: No implementation found for java.lang.String dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString() (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString and Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString__)
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.dji.importSDKDemo, PID: 5379
    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString() (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString and Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString__)
        at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>()
        at com.dji.importSDKDemo.MainActivity$1.run(Unknown Source)
`

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32984'>Zendesk ticket #32984</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry, the MSDK doesn't support the emulator.
Please use a real device to try it again.

Thanks,

Luce Luo
DJI Dev Team

**Comment by mario-s** [comment]
Thanks for the answer! As I also figured out later, it works only on a real device.
