### ISSUE TITLE
class DJIError and DJISDKError not available

### ISSUE THREAD

**Issue by adityajain07** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#5]
There is a typo in the tutorial as well as the code in MainActivity.java

The two import modules should be:

import dji.common.error.DJIError;
import dji.common.error.DJISDKError;

instead of:

import dji.sdk.base.DJIError;
import dji.sdk.base.DJISDKError;

**Comment by oliverou** [comment]
Hi @adityajain07, thanks for the feedbacks! Already fixed it!

**Comment by adityajain07** [comment]
Can you change in the documentation as well? Will be helpful for those attempting in future.

Thanks

**Comment by oliverou** [comment]
Hi @adityajain07, yes, already update the documentation on DJI Developer Website, thanks!

**Comment by adityajain07** [comment]
Thanks :)
