### ISSUE TITLE
Import SDK Demo app is not working

### ISSUE THREAD

**Issue by santhoshbn** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#6]
This demo app not is working on my Samsung Galaxy S7 Edge device with Android 6.0.1 OS.
Internet connectivity to the device is fine, I imported the project to Android Studio, install and run.
Android Studio Version : 2.3.1
Gradle Version set as : 2.10
App Key is also generated and inserted in the Manifest file.

Below is the app screen shot with error message.

![dji_importsdk_error](https://cloud.githubusercontent.com/assets/28552697/25834760/98c0fb00-3497-11e7-82bb-0039c43389f4.jpg)

**Comment by santhoshbn** [comment]
Its a firewall issue, works fine if there is no firewall.

**Comment by ChrisYin** [comment]
Hello, santhoshbn.
How do you fix this issue finally?
I've tried VPN and Shadowsocks in Android, but it didn't work. @santhoshbn

**Comment by santhoshbn** [comment]
For me it was firewall issue at my office.
 I used my mobile internet and it worked. Register sdk success toat message
should come when u connect mobile to drone's RC. One more thing, you must
clear default setting in app setting of dji go 4 app.

**Comment by oliverou** [comment]
Hi @santhoshbn , @ChrisYin , please try to use your Android 4G network instead, maybe it's the firewall issue of the router in your office or apartment. For this demo, it's not necessary to connect the app to your DJI Product to see the toast message though.
