### ISSUE TITLE
Register SDK failed: The metadata received from server is invalid

### ISSUE THREAD

**Issue by ChrisYin** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#7]
Crash logs:

```
08-09 03:59:13.459 22370-22418/com.dji.importSDKDemo I/n: ConnectivityManager says we are online
08-09 03:59:13.471 22370-22486/com.dji.importSDKDemo D/Previewer.cpp: Previewer::setAuthValue()
08-09 03:59:13.472 22370-22486/com.dji.importSDKDemo D/Previewer.cpp: Previewer::setAuthValue()
**08-09 03:59:13.473 22370-22396/com.dji.importSDKDemo D/com.dji.importSDKDemo.MainActivity: The metadata received from server is invalid, please reconnect to the server and try.**
**08-09 03:59:13.474 22370-22396/com.dji.importSDKDemo E/TAG: The metadata received from server is invalid, please reconnect to the server and try.**
08-09 03:59:13.628 22370-22370/com.dji.importSDKDemo D/DJIRemoteVersionInfo: UpgradeConfigInfo getFile for net success
08-09 03:59:16.563 22370-22417/com.dji.importSDKDemo I/n: ConnectivityManager says we are online
08-09 03:59:19.586 22370-22418/com.dji.importSDKDemo I/n: ConnectivityManager says we are online
08-09 03:59:21.442 22370-22396/com.dji.importSDKDemo I/n: ConnectivityManager says we are online
```
Error: 

> **08-09 03:59:13.473 22370-22396/com.dji.importSDKDemo D/com.dji.importSDKDemo.MainActivity: The metadata received from server is invalid, please reconnect to the server and try.**

> **08-09 03:59:13.474 22370-22396/com.dji.importSDKDemo E/TAG: The metadata received from server is invalid, please reconnect to the server and try.**

-  DJI Android SDK version : DJI Mobile SDK 4.2.1
-  Android system version : Android 7.1
-  Android device : OnePlus One
-  Android Studio version : 2.3.2
I've inserted the API key in it. I guess the reason is that Chinese firewall, but I've tried VPN and Shadowsocks. It didn't work, too. 
@oliverou

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by dji-dev** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by oscarmore2** [comment]
Hey dude:
We have been integrated the Dji Sdk for three months, we were persistently using our app without any problem, until today I encountered a wired error that shows our app fail to register in one of our Huawei phone. 
We have checked our AndroidManifest, the app key is correct, and network is totally connectable. And we also test our app at xiaomi phone, and xiaomi phone works fine.
But no matter how I workaround, the app is just won't register correctly, and  here is the log:
```
08-28 15:32:23.959 23167 23249 E MANAGER : --) no manifests dir
08-28 15:32:29.439 23167 23310 D FP      : --) Product changed NEW: dji.internal.camera.a@aaa08c1 OLD:null
08-28 15:32:29.447 23167 23310 D FP      : --) Product changed NEW: dji.sdk.gimbal.g@8460ef9 OLD:null
08-28 15:32:29.460 23167 23310 D FP      : --) Product changed NEW: dji.sdk.flightcontroller.d@c4fa1b5 OLD:null
08-28 15:32:29.463 23167 23310 D FP      : --) Product changed NEW: dji.sdk.battery.d@fa47733 OLD:null
08-28 15:32:29.467 23167 23310 D FP      : --) Product changed NEW: dji.sdk.airlink.AirLink@ecad452 OLD:null
08-28 15:32:29.474 23167 23310 D FP      : --) Product changed NEW: dji.sdk.remotecontroller.e@c627dd9 OLD:null
08-28 15:32:32.838 23167 23310 E FP      : --) register app failed: The metadata received from server is invalid, please reconnect to the server and try.
08-28 15:32:32.846 23167 23310 E FP      : --) dji app register failed
08-28 15:32:43.964 23167 23249 E MANAGER : --) no manifests dir
```
* DJI Android SDK version : DJI Mobile SDK 4.8
* Android system version : Android 9
* Device: Huawei P10 Plus
* Android Studio version: 3.4.1
