### ISSUE TITLE
Build gradle failed after adding DJI module dependencies

### ISSUE THREAD

**Issue by phongnhhn92** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#8]
Hello,
I am just followed all the step in this tutorial https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html but I stuck at the part to build gradle after adding DJI module dependencies. This is my error, please help me ! 
![capture](https://user-images.githubusercontent.com/11288381/29548337-f593f1fc-873a-11e7-896e-a6ba687cf8e8.PNG)

**Comment by oliverou** [comment]
Hi @phongnhhn92, you have missed a step in the tutorial:

In the AndroidManifest.xml file, before `android:icon="@mipmap/ic_launcher` insert : 

~~~xml
tools:replace="android:icon"
~~~

![fixmanifesterror-5c09f0cf52](https://user-images.githubusercontent.com/13310805/29549473-1fe96144-873b-11e7-9e78-3ac4d37926c8.png)


Please check the tutorial for details: <http://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html>

**Comment by phongnhhn92** [comment]
Hello,
Thanks for quick reply ! I added the lines just as you suggested but now i have this error. 
![capture](https://user-images.githubusercontent.com/11288381/29552939-486c6d00-8754-11e7-8e9f-4185bcc528a5.PNG)

Also one thing I notice is that even though I import all needed library but I encounter several error in the MainActivity.java. I dont know which step am i missing here ? 
![capture2](https://user-images.githubusercontent.com/11288381/29552953-58290316-8754-11e7-966b-2014e9325ad8.PNG)
This is my build gradle looks like
![capture3](https://user-images.githubusercontent.com/11288381/29552974-6d287404-8754-11e7-9b3c-8e42c0bed333.PNG)

**Comment by dji-dev** [comment]
Our tutorial has been updated.
It should not have this problem any more.
Will go ahead and close this issue.
@phongnhhn92 please feel free to reopen the issue if you still have problem.
